// Generated by MambaScript 0.5.5 
var present = console.log; 
// Generated by MambaScript 0.5.5 
void function () {
  var app, converter, db, express, fs, getFirstPost, json, leads, Mamba, MambaView, matter, MONGODB_URI, mongoose, path, pillar, PORT, showdown, updateLead;
  require('dotenv').config();
  Mamba = require('mambascript');
  Mamba.register();
  MambaView = Mamba.MambaView;
  express = require('express');
  app = express();
  fs = require('fs');
  path = require('path');
  json = '' + __dirname + '/json';
  pillar = '' + __dirname + '/json_pillar';
  PORT = process.env.PORT || 8089;
  matter = require('gray-matter');
  showdown = require('showdown');
  converter = new showdown.Converter;
  mongoose = require('mongoose');
  leads = require('./models/leadController.mamba');
  updateLead = require('./models/updateLead.mamba');
  MONGODB_URI = process.env.MONGO_URI;
  db = mongoose.connection;
  mongoose.connect(MONGODB_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  db.on('open', function () {
    return present('Connected to Mongo');
  });
  app.use(express.json());
  app.use(express.urlencoded({ extended: true }));
  app.set('views', './src');
  app.set('view engine', 'mamba');
  app.engine('mamba', require('./engine.js').createEngine());
  app.use(express['static']('public'));
  app.use('/addLead', leads);
  app.get('/linkedin', function (req, res) {
    return res.redirect('https://linkedin.com/in/bigpoppacode');
  });
  app.get('/twitter', function (req, res) {
    return res.redirect('https://twitter.com/bigpoppacode');
  });
  app.get('/youtube', function (req, res) {
    return res.redirect('https://youtube.com/@bigpoppacode');
  });
  app.get('/instagram', function (req, res) {
    return res.redirect('https://instagram.com/bigpoppacode');
  });
  app.get('/portfolio', function (req, res) {
    return res.redirect('https://github.com/arthurbernierjr');
  });
  getFirstPost = function (req, res, next) {
    return fs.readFile('' + pillar + '/start-here.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        res.locals = JSON.parse(file);
        return next();
      }
    });
  };
  app.get('/', getFirstPost, function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile('/public/index.html');
  });
  app.get('/case-study', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', 'main.html'));
  });
  app.get('/allposts', function (req, res) {
    return fs.readFile('' + json + '/all.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/Blog', {
          posts: JSON.parse(file).sort(function (a, b) {
            return a.data.order - b.data.order;
          })
        });
      }
    });
  });
  app.get('/about', function (req, res) {
    return fs.readFile('' + json + '_static/about.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/About', { post: JSON.parse(file) });
      }
    });
  });
  app.get('/contact', function (req, res) {
    return fs.readFile('' + json + '_static/contact.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/Contact', { post: JSON.parse(file) });
      }
    });
  });
  app.get('/chatgpt', function (req, res) {
    return fs.readFile('' + json + '_static/chat-gpt-prompts-goldmine.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/Show', { post: JSON.parse(file) });
      }
    });
  });
  app.get('/projects', function (req, res) {
    return fs.readFile('' + json + '_static/projects.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/Projects', { post: JSON.parse(file) });
      }
    });
  });
  app.get('/programs', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'investfest.html'));
  });
  app.get('/programs/:name', function (req, res) {
    return fs.readFile('' + json + '_static/' + req.params.name + '.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/Program', { post: JSON.parse(file) });
      }
    });
  });
  app.get('/a7575/ai-in-digital-marketing', function (req, res) {
    return fs.readFile('' + json + '_static/ai-digital.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/Program', { post: JSON.parse(file) });
      }
    });
  });
  app.get('/go/drumar', function (req, res) {
    return res.redirect('https://youtu.be/kVV0g1FIBSg');
  });
  app.get('/go/roadtoqa', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.redirect('https://youtu.be/2wmzcWVPkhM');
  });
  app.get('/go/mattyj', function (req, res) {
    return res.redirect('https://youtu.be/kVV0g1FIBSg');
  });
  app.get('/go/ai-in-digital-marketing-video', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', 'main.html'));
  });
  app.get('/go/5million', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', '5Million.html'));
  });
  app.get('/go/mini-portfolio', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', 'mini-portfolio.html'));
  });
  app.get('/go/code-different', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', 'code-different.html'));
  });
  app.get('/go/code', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', 'code-different.html'));
  });
  app.get('/go/code-class', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', 'code-1.html'));
  });
  app.get('/go/5Million', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', '5Million.html'));
  });
  app.get('/go/digitalbossode', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.redirect('https://www.skool.com/digitalbosscode/about?ref=e3a89aaa604f4418b93b6e5d316026fe');
  });
  app.get('/go/digitalbosscode', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.redirect('https://www.skool.com/digitalbosscode/about?ref=e3a89aaa604f4418b93b6e5d316026fe');
  });
  app.get('/go/dbc', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.redirect('https://www.skool.com/digitalbosscode/about?ref=e3a89aaa604f4418b93b6e5d316026fe');
  });
  app.get('/go/dbav1', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.redirect('https://shop.beacons.ai/bigpoppacode/294f680a-f5b0-42bd-94e8-2f2ca348c08d');
  });
  app.get('/go/dbav2', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.redirect('https://shop.beacons.ai/bigpoppacode/28d2461b-4180-4087-bdc6-d3225ab06ed8');
  });
  app.get('/go/dbav3', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.redirect('https://shop.beacons.ai/bigpoppacode/34ac8abb-79f4-45cd-8d9d-4cf3bcae5d6f');
  });
  app.get('/go/2032', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', '2032.html'));
  });
  app.get('/go/2032/thankyou/4d3b987a3381f0b3b8f0cc44da78432deab50b88872f6faddf7e8b585e4e98dc', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', '2032thankyou.html'));
  });
  app.get('/go/27', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', '27.html'));
  });
  app.get('/go/ai-bonus', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', 'ai-bonus.html'));
  });
  app.get('/go/build-your-own-empire', function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', '27.html'));
  });
  app.get('/go/27/thankyou/4d3b987a3381f0b3b8f0cc44da78432deab50b88872f6faddf7e8b585e4e98dc', updateLead, function (req, res) {
    res.setHeader('Content-Type', 'text/html');
    return res.sendFile(path.resolve(__dirname, 'public', '27thankyou.html'));
  });
  app.get('/go/2032/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', '2032-survival-guide.pdf'));
  });
  app.get('/go/27/5million/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', '5million.pdf'));
  });
  app.get('/go/27/tewb/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'tewb.pdf'));
  });
  app.get('/go/27/confessions/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'confessions.pdf'));
  });
  app.get('/go/27/quickstart/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'quickstartguide.pdf'));
  });
  app.get('/go/27/bonus1/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'bonus1.pdf'));
  });
  app.get('/go/27/bonus2/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'bonus2.pdf'));
  });
  app.get('/go/27/bonus3/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'bonus3.pdf'));
  });
  app.get('/go/27/bonus4/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'bonus4.pdf'));
  });
  app.get('/go/27/bonus5/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'bonus5.pdf'));
  });
  app.get('/go/27/bonus6/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'bonus6.pdf'));
  });
  app.get('/go/27/bonus7/qwertyuiopxz', function (req, res) {
    return res.sendFile(path.resolve(__dirname, 'public', 'guides', 'bonus7.pdf'));
  });
  app.get('/start-here', function (req, res) {
    return fs.readFile('' + pillar + '/start-here.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/Show', { post: JSON.parse(file) });
      }
    });
  });
  app.get('/perscholas-cheatsheet', function (req, res) {
    return fs.readFile('' + pillar + '/git.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/Show', { post: JSON.parse(file) });
      }
    });
  });
  app.get('/:post', function (req, res) {
    return fs.readFile('' + json + '/' + req.params.post + '.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.render('pages/Show', { post: JSON.parse(file) });
      }
    });
  });
  app.get('/api/posts', function (req, res) {
    return fs.readFile('' + json + '/all.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.status(200).json(JSON.parse(file));
      }
    });
  });
  app.get('/api/:post', function (req, res) {
    return fs.readFile('' + json + '/' + req.params.post + '.json', 'utf8', function (err, file) {
      if (err) {
        return console.error(err);
      } else {
        return res.status(200).json(JSON.parse(file));
      }
    });
  });
  app.listen(PORT, function () {
    return present('API Listening on port ' + PORT);
  });
}.call(this);